export {
	addBuildIDListener,
	addRouteChangeListener,
	addStatusListener,
	devRevalidate,
	getBuildID,
	getCurrentHwyData,
	getPrefetchHandlers,
	getStatus,
	initClient,
	internal_HwyClientGlobal,
	makeLinkClickListenerFn,
	navigate,
	revalidate,
	submit,
	type RouteChangeEvent,
	type StatusEvent,
} from "./src/client.js";
